language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
install: 
  - pip install -r requirements-dev.txt
  - pip install -U tox codecov
script: 
  - tox
after_success:
- codecov
